### PR TITLE
Fix #349 retry on jobInternalError

### LINKED ISSUE #349: ERROR : INVALID_ARGUMENT jobInternalError
From time to time, we have a jobInternalError 

The jobInternalError is a broad error message, and it can be triggered by various underlying issues.
It can be a temporary network error on our side, or a temporary issue on GCP but it's a problem to have to manually restart the connector each time this happen.

After the connector restart everything is fine and run smoothly again 

If this error is caused by temporary general issues, couldn't be better to consider it as a Retryable error instead of just crashing the connector task ?

The error from GCP : 
```
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "The job encountered an internal error during execution and was unable to complete successfully.",
    "reason" : "jobInternalError"
  } ],
  "message" : "The job encountered an internal error during execution and was unable to complete successfully.",
  "status" : "INVALID_ARGUMENT"
}
```

The stacktrace : 
```
ERROR WorkerSinkTask{id=connector_sink_bigquery-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: A write thread has failed with an unrecoverable error (org.apache.kafka.connect.runtime.WorkerSinkTask:566)
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: A write thread has failed with an unrecoverable error
Caused by: The job encountered an internal error during execution and was unable to complete successfully.
	at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.lambda$maybeThrowEncounteredError$0(KCBQThreadPoolExecutor.java:101)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.maybeThrowEncounteredError(KCBQThreadPoolExecutor.java:100)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.writeSinkRecords(BigQuerySinkTask.java:251)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.put(BigQuerySinkTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.cloud.bigquery.BigQueryException: The job encountered an internal error during execution and was unable to complete successfully.
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:643)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1393)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1388)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1387)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1371)
	at com.google.cloud.bigquery.Job$1.call(Job.java:338)
	at com.google.cloud.bigquery.Job$1.call(Job.java:335)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334)
	at com.google.cloud.bigquery.Job.getQueryResults(Job.java:295)
	at com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1335)
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1283)
	at com.wepay.kafka.connect.bigquery.MergeQueries.mergeFlush(MergeQueries.java:153)
	at com.wepay.kafka.connect.bigquery.MergeQueries.lambda$mergeFlush$1(MergeQueries.java:130)
	... 3 more
```

### PR DESCRIPTION
**Pull request by SebHeuze**
This is a fix for #349 to retry when the error is a jobInternalError (400)

After contacting support this error should be rare and can happen during system overload 
The documentation mention this "Retry the job with a new jobId. If the error continues to occur, contact support."

So I reused the existing catch for the retriable serialization error, since this error happen during system overload it can be relevant to wait few seconds before retrying.

I am open to any suggestion.

### CODE REVIEW

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java [hunk 1]
```diff
@@ -153,13 +151,13 @@ private void mergeFlush(
           bigQuery.query(QueryJobConfiguration.of(mergeFlushQuery));
           success = true;
         } catch (BigQueryException e) {
-          if (BigQueryErrorResponses.isCouldNotSerializeAccessError(e)) {
+          if (BigQueryErrorResponses.isCouldNotSerializeAccessError(e) || BigQueryErrorResponses.isJobInternalError(e)) {
```
Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:154]: Lets use `bigQueryRetry` config to decide the retry count for isJobInternalError

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java [hunk 2]
```diff
@@ -153,13 +151,13 @@ private void mergeFlush(
...
             attempt++;
             if (attempt == 30) {
-              throw new BigQueryConnectException("Failed to merge rows to destination table `" + destinationTable + "` within " + attempt 
-                                                  + "  attempts due to BQ write serialization error.", e);
+              throw new BigQueryConnectException("Failed to merge rows to destination table `" + destinationTable + "` within " + attempt
+                      + "  attempts.", e);
             }
-            SleepUtils.waitRandomTime(10000, 20000);
+            waitRandomTime(10000, 20000);
```
Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:160]: Lets add a `warn` log to keep the user informed that retries are happening.

Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:160]: `bigQueryRetryWait`  for calculating sleep

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java [hunk 3]
```diff
@@ -481,6 +479,10 @@ static String batchClearQuery(TableId intermediateTable, int batchNumber) {
         .toString();
   }
 
+  public void waitRandomTime(int sleepMs, int jitterMs) throws InterruptedException {
```
Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:482]: SleepUtils looks like the right place for this. Any reasons for moving it to MergeQueries?

**Review by b-goyal — CHANGES_REQUESTED** [review]
Thanks for the PR @SebHeuze . Left some minor comments. Could you take a look at those please. Will be taking a look at tests in next pass.

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java (hunk 3 above)
Comment (SebHeuze) [reply kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java]: That was because the current sleep call in MergeQueries had hardcoded values and static so it was annoying for testing, since BigqueryWriter has a method waitRandomTime I made the same thing in MergeQueries so I was able to modify the sleep call in test.
But now we use config for sleepMs and maxRetry so the problem is not here anymore I recreated SleepUtils

**Comment by SebHeuze** [comment]
I edited my PR based on the last reviews, 
I edited the class so it now use configurable retry max count and retryWait, the MAX Jitter has been set to 1000 (based on what value other class use) instead of 10000 (I think it does not make sense to leave 10000 jitter since the default bigQueryRetryWait is 1000 ?)

Both retriable exception in this class now use bigQueryRetry and bigQueryRetryWait, does it look good to you or you want to leave the current hardcoded 10s-20s sleep and 30 maxRetry that was used until now for SerializeAccessError ?  

I added another test that ensure it throw an exception after X retry

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java [hunk 4]
```diff
@@ -150,16 +160,21 @@ private void mergeFlush(
...
+          }
           bigQuery.query(QueryJobConfiguration.of(mergeFlushQuery));
           success = true;
         } catch (BigQueryException e) {
-          if (BigQueryErrorResponses.isCouldNotSerializeAccessError(e)) {
+          if (attempt >= bigQueryRetry) {
+            throw new BigQueryConnectException("Failed to merge rows to destination table `" + destinationTable + "` within " + attempt
+              + "  attempts.", e);
+          } else if (BigQueryErrorResponses.isCouldNotSerializeAccessError(e)) {
+            logger.warn("Serialization error while merging from {} to {}, attempting retry", intermediateTable, destinationTable);
```
Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:173]:
```suggestion
            logger.warn("Serialization error while merging from {} to {}, retry attempt {}", intermediateTable, destinationTable, ++attempt);
```

File: kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java [hunk 5]
```diff
@@ -150,16 +160,21 @@ private void mergeFlush(
...
+            attempt++;
+          } else if (BigQueryErrorResponses.isJobInternalError(e)) {
+            logger.warn("Job internal error while merging from {} to {}, attempting retry", intermediateTable, destinationTable);
```
Comment (b-goyal) [inline kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/MergeQueries.java:176]: same ^

File: kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java [hunk 6]
```diff
@@ -19,11 +19,8 @@
 
 package com.wepay.kafka.connect.bigquery;
 
-import com.google.cloud.bigquery.BigQuery;
-import com.google.cloud.bigquery.Field;
-import com.google.cloud.bigquery.LegacySQLTypeName;
-import com.google.cloud.bigquery.Schema;
-import com.google.cloud.bigquery.TableId;
+import com.google.cloud.bigquery.*;
```
Comment (b-goyal) [inline kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java:22]: Please import individual classes and avoid use of `.*`

File: kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java [hunk 7]
```diff
@@ -38,16 +35,21 @@
 import java.util.Arrays;
 import java.util.HashMap;
 import java.util.List;
+import java.util.concurrent.CountDownLatch;
 
 import static org.junit.Assert.assertEquals;
-import static org.mockito.Mockito.when;
+import static org.mockito.ArgumentMatchers.any;
+import static org.mockito.ArgumentMatchers.anyObject;
+import static org.mockito.Mockito.*;
```
Comment (b-goyal) [inline kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/MergeQueriesTest.java:43]: same^

**Review by b-goyal — CHANGES_REQUESTED** [review]
Thankyou @SebHeuze for taking time and looking into the comments. 
Left 2 minor comments, could you take a look please. Would be good to merge once those are resolved. Thanks!

**Comment by b-goyal** [comment]
@SebHeuze , would you be able to target these changes to 2.5.x and change the base branch to 2.5.x please.

**Review by b-goyal — APPROVED** [review]
Looks good, thanks @SebHeuze
